trigger:
- master

pool: demo-lab-pool

variables:
  DOCKER_IMAGE: 'javierk38/demo-lab'
  DOCKER_REGISTRY: 'dockerHub'
  

jobs:
- job: SonarQubeAnalysis
  displayName: 'Run SonarQube Analysis'
  steps:

  - script: |
      cd app
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - task: SonarQubePrepare@6
    inputs:
      SonarQube: 'demo-lab-sonar'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'demo-lab_demo-lab_65daae9f-22b4-428b-9683-f80f0c126e2a'
      cliSources: 'app'
      extraProperties: |
        sonar.python.version=3
        sonar.projectVersion=1.0
    displayName: 'Prepare SonarQube analysis'
  - task: SonarQubeAnalyze@6
  - task: SonarQubePublish@6
    inputs:
      pollingTimeoutSec: '300'

- job: DockerBuildPush
  displayName: 'Build and Push Docker Image'
  dependsOn: SonarQubeAnalysis
  condition: succeeded()

  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerHub'
      command: 'login'
  - task: Docker@2
    inputs:
      containerRegistry: '$(DOCKER_REGISTRY)'
      repository: '$(DOCKER_IMAGE)'
      command: 'buildAndPush'
      Dockerfile: 'app/Dockerfile'
      buildContext: 'app'
      tags: '$(Build.BuildId)'

- job: HelloWorld
  displayName: 'Imprimir Hola Mundo 10 veces'
  pool: demo-lab-pool
  steps:
  - script: |
      for i in {1..10}
      do
        echo "Hola Mundo"
      done
    displayName: 'ECHO Hola Mundo 10 veces'

- job: CreateFiles
  displayName: 'Crear archivos e imprimirlos'
  pool: demo-lab-pool
  steps:
  - script: |
      for i in {1..10}
      do
        echo "$(date)" > "file_$i.txt"
        cat "file_$i.txt"
      done
      ls
    displayName: 'Create 10 files with date and display them'
