apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-lab-deployment
  labels:
    app: demo-lab
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-lab
  template:
    metadata:
      labels:
        app: demo-lab
    spec:
      containers:
      - name: demo-lab
        image: javierk38/demo-lab:TAG_PLACEHOLDER #este tag se cambia por el tag que se compila en el build de docker
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
